# 1. NumPy Operations

In [1]:
import os
import numpy as np
import pandas as pd

In [3]:
# 1. Create a 6x4 array with random integers from 0 to 100
arr1 = np.random.randint(0,101,size=(6,4))
arr1

array([[ 83,   3,  79,  94],
       [  6,   4,  77,  83],
       [  2, 100,  83,  66],
       [100,  96,  55,  14],
       [ 21,  17,  75,  50],
       [ 70,  79,  70,  99]])

In [5]:
# 2. Row-wise and Column-wise Means and Standard Deviations
np.mean(arr1,axis=0)

array([47.        , 49.83333333, 73.16666667, 67.66666667])

In [7]:
np.std(arr1, axis=0)

array([38.76424469, 42.5653093 ,  9.02619644, 29.16999981])

In [9]:
np.mean(arr1,axis=1)

array([64.75, 42.5 , 62.75, 66.25, 40.75, 79.5 ])

In [11]:
np.std(arr1,axis=1)

array([36.07197666, 37.56660751, 37.07677845, 34.93118234, 23.51993835,
       11.84271928])

In [13]:
# 3. Boolean indexing: values > 50
gt_50 = arr1[arr1>50]
gt_50

array([ 83,  79,  94,  77,  83, 100,  83,  66, 100,  96,  55,  75,  70,
        79,  70,  99])

In [15]:
# 4. Replace even numbers with -1
e_arr = np.where(arr1%2==0, -1, arr1)
e_arr

array([[83,  3, 79, -1],
       [-1, -1, 77, 83],
       [-1, -1, 83, -1],
       [-1, -1, 55, -1],
       [21, 17, 75, -1],
       [-1, 79, -1, 99]])

In [17]:
# 5. Normalize the array (subtract mean and divide by std).
mean = arr1.mean()
mean

59.416666666666664

In [19]:
std = arr1.std()
std

34.46002111948795

In [21]:
nor_arr = (arr1-mean)/std
nor_arr

array([[ 0.68436793, -1.63716286,  0.56829139,  1.00357841],
       [-1.55010545, -1.60814372,  0.51025312,  0.68436793],
       [-1.66618199,  1.17769322,  0.68436793,  0.19104264],
       [ 1.17769322,  1.06161668, -0.12816785, -1.31795237],
       [-1.11481843, -1.23089497,  0.45221485, -0.27326352],
       [ 0.30711918,  0.56829139,  0.30711918,  1.14867409]])

In [23]:
# 6. Create a 3D array of shape (3, 4, 5) with random floats
arr_3d = np.random.rand(3,4,5)
arr_3d

array([[[0.36134854, 0.80198331, 0.00330485, 0.87132136, 0.99891183],
        [0.84989793, 0.74853115, 0.00278889, 0.8834555 , 0.60027743],
        [0.8139085 , 0.31639545, 0.79735262, 0.11679056, 0.89279741],
        [0.48699534, 0.40487397, 0.64081261, 0.60552902, 0.25021284]],

       [[0.97791743, 0.96143965, 0.42728335, 0.70988676, 0.632371  ],
        [0.00782015, 0.83579265, 0.95243697, 0.07851855, 0.11638261],
        [0.65682939, 0.34751484, 0.93581349, 0.32657694, 0.99745425],
        [0.77077809, 0.31429411, 0.023588  , 0.02770867, 0.83399087]],

       [[0.26644215, 0.84920949, 0.61842477, 0.79807141, 0.87310002],
        [0.66300154, 0.84045602, 0.01247286, 0.2346601 , 0.75606758],
        [0.80811912, 0.47767054, 0.09304121, 0.7529974 , 0.17500828],
        [0.43766252, 0.46301797, 0.30187521, 0.93499294, 0.82428884]]])

In [25]:
# 7. Convert list of lists to NumPy array, get shape and size
ls=[[1,2,3],[4,5,6]]
ls_ar=np.array(ls)
ls_ar.shape

(2, 3)

In [27]:
ls_ar.size

6

In [29]:
#8. Create an identity matrix and add it to a random matrix of the same size.
id_mat=np.eye(4)
id_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
random_mat=np.random.rand(4,4)
random_mat

array([[0.80527982, 0.69728462, 0.01450397, 0.42014519],
       [0.7572986 , 0.43301444, 0.09771206, 0.40219628],
       [0.14384611, 0.22237928, 0.30978229, 0.86011444],
       [0.15368393, 0.15104858, 0.03971003, 0.61898145]])

In [33]:
#9.	Flatten a 2D array and reshape it into a different valid shape.
flat_arr=ls_ar.flatten()
flat_arr

array([1, 2, 3, 4, 5, 6])

In [35]:
flat_arr.shape

(6,)

In [37]:
reshap=flat_arr.reshape(2,3)
reshap

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# 10. Use broadcasting to subtract the column mean from a 2D array.
col_mean=arr1.mean(axis=0)
col_mean

array([47.        , 49.83333333, 73.16666667, 67.66666667])

In [41]:
broad_cast=arr1-col_mean
broad_cast

array([[ 36.        , -46.83333333,   5.83333333,  26.33333333],
       [-41.        , -45.83333333,   3.83333333,  15.33333333],
       [-45.        ,  50.16666667,   9.83333333,  -1.66666667],
       [ 53.        ,  46.16666667, -18.16666667, -53.66666667],
       [-26.        , -32.83333333,   1.83333333, -17.66666667],
       [ 23.        ,  29.16666667,  -3.16666667,  31.33333333]])

In [43]:
#11. Simulate 1000 dice rolls and calculate the frequency of each face (1–6).
dic_rol=np.random.randint(1,7,size=1000)
dic_rol

array([1, 1, 5, 1, 6, 3, 5, 5, 4, 5, 5, 2, 2, 3, 6, 3, 2, 4, 2, 2, 2, 6,
       5, 3, 2, 5, 2, 3, 4, 2, 5, 6, 5, 6, 6, 6, 4, 5, 4, 2, 1, 3, 1, 1,
       3, 4, 6, 4, 6, 6, 4, 2, 1, 3, 4, 1, 4, 3, 2, 1, 4, 1, 6, 6, 1, 5,
       1, 3, 6, 3, 1, 5, 2, 1, 5, 3, 4, 6, 2, 2, 1, 3, 4, 3, 5, 5, 6, 1,
       6, 4, 1, 5, 3, 5, 4, 1, 6, 5, 6, 5, 2, 3, 6, 6, 4, 2, 5, 2, 4, 3,
       2, 6, 6, 3, 5, 6, 4, 3, 2, 6, 4, 2, 1, 2, 4, 1, 2, 2, 4, 5, 6, 3,
       5, 3, 3, 4, 1, 5, 2, 4, 1, 4, 2, 4, 3, 2, 4, 5, 5, 3, 6, 4, 1, 5,
       4, 3, 2, 2, 6, 3, 6, 4, 1, 6, 3, 6, 4, 6, 6, 2, 2, 2, 5, 4, 3, 6,
       2, 2, 3, 6, 2, 3, 6, 5, 3, 4, 1, 2, 6, 2, 3, 3, 5, 1, 1, 1, 6, 5,
       2, 2, 2, 6, 4, 6, 6, 2, 1, 2, 3, 4, 3, 5, 5, 1, 6, 2, 2, 5, 2, 3,
       5, 1, 1, 5, 3, 1, 1, 2, 5, 5, 2, 5, 3, 4, 3, 6, 3, 3, 2, 1, 3, 6,
       6, 5, 2, 6, 3, 3, 5, 6, 3, 3, 1, 4, 6, 5, 2, 2, 6, 4, 4, 3, 3, 3,
       6, 4, 6, 1, 4, 5, 2, 1, 4, 6, 6, 4, 3, 2, 3, 1, 4, 6, 6, 5, 2, 3,
       1, 4, 4, 4, 6, 5, 6, 6, 4, 3, 6, 5, 6, 6, 6,

In [45]:
dic_rol.size

1000

In [47]:
(uniq,cout)=np.unique(dic_rol,return_counts=True)
(uniq,cout)

(array([1, 2, 3, 4, 5, 6]), array([157, 165, 160, 175, 169, 174], dtype=int64))

In [49]:
freq=dict(zip(uniq,cout))
freq

{1: 157, 2: 165, 3: 160, 4: 175, 5: 169, 6: 174}

In [51]:
#12.Find the top 3 largest values in a NumPy array without sorting the whole array.
flat_arr=arr1.flatten()
flat_arr

array([ 83,   3,  79,  94,   6,   4,  77,  83,   2, 100,  83,  66, 100,
        96,  55,  14,  21,  17,  75,  50,  70,  79,  70,  99])

In [53]:
top_3 = np.partition(flat_arr,-3)[-3:]
top_3

array([ 99, 100, 100])

In [55]:
#14.Generate 1 million random num and calculate the percentiles (25th, 50th, 75th).
ran_1m=np.random.rand(1000000)

In [57]:
p_25=np.percentile(ran_1m,25)
p_25

0.24983324763848033

In [59]:
p_50=np.percentile(ran_1m,50)
p_50

0.49997960191442314

In [61]:
p_75=np.percentile(ran_1m,75)
p_75

0.7498910453770524

# Part 2: Data Cleaning with Pandas

In [66]:
# 1. Load the first sheet of the Excel file into a DataFrame
df = pd.read_excel('online_retail.xlsx',sheet_name='Year 2010-2011')
df.head()

Invoice StockCode                          Description  Quantity  \
0  536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1  536365     71053                  WHITE METAL LANTERN         6   
2  536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3  536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4  536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  Price  Customer ID         Country  
0 2010-12-01 08:26:00   2.55      17850.0  United Kingdom  
1 2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
2 2010-12-01 08:26:00   2.75      17850.0  United Kingdom  
3 2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
4 2010-12-01 08:26:00   3.39      17850.0  United Kingdom

In [67]:
# 2. Display the first 5 and last 5 rows
df.tail()

Invoice StockCode                      Description  Quantity  \
541905  581587     22899     CHILDREN'S APRON DOLLY GIRL          6   
541906  581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4   
541907  581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4   
541908  581587     22138    BAKING SET 9 PIECE RETROSPOT          3   
541909  581587      POST                          POSTAGE         1   

               InvoiceDate  Price  Customer ID Country  
541905 2011-12-09 12:50:00   2.10      12680.0  France  
541906 2011-12-09 12:50:00   4.15      12680.0  France  
541907 2011-12-09 12:50:00   4.15      12680.0  France  
541908 2011-12-09 12:50:00   4.95      12680.0  France  
541909 2011-12-09 12:50:00  18.00      12680.0  France

In [68]:
# 3. Check for missing values per column
df.isnull().sum()

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [69]:
# 4. Drop rows with missing Customer ID
df0=df.dropna(subset=['Customer ID'])
df0

Invoice StockCode                          Description  Quantity  \
0       536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1       536365     71053                  WHITE METAL LANTERN         6   
2       536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3       536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4       536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...        ...       ...                                  ...       ...   
541905  581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906  581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907  581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908  581587     22138        BAKING SET 9 PIECE RETROSPOT          3   
541909  581587      POST                              POSTAGE         1   

               InvoiceDate  Price  Customer ID         Country  
0      2010-12-01 08:26:00   2.55      17850.0  United Kingdom  
1      2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
2      2010-12-01 08:26:00   2.75      17850.0  United Kingdom  
3      2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
4      2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
...                    ...    ...          ...             ...  
541905 2011-12-09 12:50:00   2.10      12680.0          France  
541906 2011-12-09 12:50:00   4.15      12680.0          France  
541907 2011-12-09 12:50:00   4.15      12680.0          France  
541908 2011-12-09 12:50:00   4.95      12680.0          France  
541909 2011-12-09 12:50:00  18.00      12680.0          France  

[406830 rows x 8 columns]

In [70]:
# 5. Drop duplicate records
df1=df0.drop_duplicates()
df1.shape

(401605, 8)

In [71]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401605 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   Invoice      401605 non-null  object        
 1   StockCode    401605 non-null  object        
 2   Description  401605 non-null  object        
 3   Quantity     401605 non-null  int64         
 4   InvoiceDate  401605 non-null  datetime64[ns]
 5   Price        401605 non-null  float64       
 6   Customer ID  401605 non-null  float64       
 7   Country      401605 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.6+ MB


In [72]:
df1.to_csv('cleaned_data.csv', index=False)

# 3: Data Exploration

In [74]:
# 1. Show the total number of unique StockCode values.
uniq_stoc = df1['StockCode'].nunique()
uniq_stoc

3684

In [75]:
#2.	Find the most frequent Description.
freq_dist = df1['Description'].value_counts().idxmax()
freq_dist

'WHITE HANGING HEART T-LIGHT HOLDER'

In [87]:
#3. Show the number of unique customers.
uniq_cust=df['Customer ID'].nunique()
uniq_cust

4372

In [91]:
#4 Count how many orders were cancelled (InvoiceNo starts with 'C').
can_ord=df[df['Invoice'].astype(str).str.startswith('C')]
can_ord

Invoice StockCode                       Description  Quantity  \
141     C536379         D                          Discount        -1   
154     C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1   
235     C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12   
236     C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24   
237     C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24   
...         ...       ...                               ...       ...   
540449  C581490     23144   ZINC T-LIGHT HOLDER STARS SMALL       -11   
541541  C581499         M                            Manual        -1   
541715  C581568     21258        VICTORIAN SEWING BOX LARGE        -5   
541716  C581569     84978  HANGING HEART JAR T-LIGHT HOLDER        -1   
541717  C581569     20979     36 PENCILS TUBE RED RETROSPOT        -5   

               InvoiceDate   Price  Customer ID         Country  
141    2010-12-01 09:41:00   27.50      14527.0  United Kingdom  
154    2010-12-01 09:49:00    4.65      15311.0  United Kingdom  
235    2010-12-01 10:24:00    1.65      17548.0  United Kingdom  
236    2010-12-01 10:24:00    0.29      17548.0  United Kingdom  
237    2010-12-01 10:24:00    0.29      17548.0  United Kingdom  
...                    ...     ...          ...             ...  
540449 2011-12-09 09:57:00    0.83      14397.0  United Kingdom  
541541 2011-12-09 10:28:00  224.69      15498.0  United Kingdom  
541715 2011-12-09 11:57:00   10.95      15311.0  United Kingdom  
541716 2011-12-09 11:58:00    1.25      17315.0  United Kingdom  
541717 2011-12-09 11:58:00    1.25      17315.0  United Kingdom  

[9288 rows x 8 columns]

In [93]:
#5 display the number of transactions per country
trans_p_country=df['Country'].value_counts()
trans_p_country

Country
United Kingdom          495478
Germany                   9495
France                    8558
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58


In [97]:
#6. Get the number of unique InvoiceNo values per customer.
uniq_inv=df.groupby('Customer ID')['Invoice'].nunique()
uniq_inv

Customer ID
12346.0     2
12347.0     7
12348.0     4
12349.0     1
12350.0     1
           ..
18280.0     1
18281.0     1
18282.0     3
18283.0    16
18287.0     3
Name: Invoice, Length: 4372, dtype: int64

In [105]:
# 7. show All transactions from a specific date (e.g., '2010-12-01')
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])
trans_date = df[df['InvoiceDate'].dt.date==pd.to_datetime('2010-12-01').date()]
trans_date

Invoice StockCode                          Description  Quantity  \
0     536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1     536365     71053                  WHITE METAL LANTERN         6   
2     536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3     536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4     536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...      ...       ...                                  ...       ...   
3103  536597    35271S                 GOLD PRINT PAPER BAG        14   
3104  536597     21380        WOODEN HAPPY BIRTHDAY GARLAND         1   
3105  536597     22909  SET OF 20 VINTAGE CHRISTMAS NAPKINS         1   
3106  536597     21221          SET/4 BADGES CUTE CREATURES         5   
3107  536597     20755             BLUE PAISLEY POCKET BOOK         6   

             InvoiceDate  Price  Customer ID         Country  
0    2010-12-01 08:26:00   2.55      17850.0  United Kingdom  
1    2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
2    2010-12-01 08:26:00   2.75      17850.0  United Kingdom  
3    2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
4    2010-12-01 08:26:00   3.39      17850.0  United Kingdom  
...                  ...    ...          ...             ...  
3103 2010-12-01 17:35:00   0.19      18011.0  United Kingdom  
3104 2010-12-01 17:35:00   2.95      18011.0  United Kingdom  
3105 2010-12-01 17:35:00   0.85      18011.0  United Kingdom  
3106 2010-12-01 17:35:00   1.25      18011.0  United Kingdom  
3107 2010-12-01 17:35:00   0.85      18011.0  United Kingdom  

[3108 rows x 8 columns]

In [109]:
#8. find the most common combination of Country and StockCode
com_combo=df.groupby(['Country','StockCode']).size().idxmax()       #most_common_country + stock_code
com_combo

('United Kingdom', '85123A')

#  Part 4: Transformations and Grouping

In [112]:
#1.	Create a column TotalPrice = Quantity × UnitPrice
df['TotalPrice'] = df['Quantity']*df['Price']
df['TotalPrice']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...  
541905    12.60
541906    16.60
541907    16.60
541908    14.85
541909    18.00
Name: TotalPrice, Length: 541910, dtype: float64

In [189]:
#2 use groupby to calculate total revenue per country
rev_per_country=df.groupby('Country')['TotalPrice'].sum().sort_values(ascending=False)
rev_per_country.head()

Country
United Kingdom    8187806.364
Netherlands        284661.540
EIRE               263276.820
Germany            221698.210
France             197421.900
Name: TotalPrice, dtype: float64

In [185]:
#3.	Use groupby to calculate:
# a. Total quantity sold per product
quantity_per_prod=df.groupby('StockCode')['Quantity'].sum().sort_values(ascending=False)
quantity_per_prod.head()

StockCode
22197     56450
84077     53847
85099B    47363
85123A    38830
84879     36221
Name: Quantity, dtype: int64

In [191]:
# 3.b. Average unit price per product
avg_pric_per_prod = df.groupby('StockCode')['Price'].mean().sort_values(ascending=False)
avg_pric_per_prod.head()

StockCode
AMAZONFEE       7324.784706
CRUK             495.839375
M                375.566392
DOT              290.495859
BANK CHARGES     202.855162
Name: Price, dtype: float64

In [201]:
#4.	Create a summary per customer:
# a	Total orders
# b	Total quantity
# c Total Revenue

summary_per_cust = df.groupby('Customer ID').agg(
    TotalOrders=('Invoice','nunique'),
    TotalQuantity=('Quantity','sum'),
    TotalRevenue=('TotalPrice','sum')
).sort_values(by='TotalRevenue',ascending=False)

summary_per_cust.head()

TotalOrders  TotalQuantity  TotalRevenue
Customer ID                                          
14646.0               77         196719     279489.02
18102.0               62          64122     256438.49
17450.0               55          69029     187482.17
14911.0              248          77180     132572.62
12415.0               26          77242     123725.45

# Part 5: Filtering and Queries

In [204]:
#1.	Filter transactions from the United Kingdom where Quantity > 10 and UnitPrice > 2.
uk_filtered = df[(df['Country']=='United Kingdom')&(df['Quantity']>10) & (df['Price']>2)]
uk_filtered.head()

Invoice StockCode                        Description  Quantity  \
46  536371     22086    PAPER CHAIN KIT 50'S CHRISTMAS         80   
65  536374     21258         VICTORIAN SEWING BOX LARGE        32   
82  536376     22114  HOT WATER BOTTLE TEA AND SYMPATHY        48   
83  536376     21733   RED HANGING HEART T-LIGHT HOLDER        64   
90  536378    84997B  RED 3 PIECE RETROSPOT CUTLERY SET        12   

           InvoiceDate  Price  Customer ID         Country  TotalPrice  
46 2010-12-01 09:00:00   2.55      13748.0  United Kingdom       204.0  
65 2010-12-01 09:09:00  10.95      15100.0  United Kingdom       350.4  
82 2010-12-01 09:32:00   3.45      15291.0  United Kingdom       165.6  
83 2010-12-01 09:32:00   2.55      15291.0  United Kingdom       163.2  
90 2010-12-01 09:37:00   3.75      14688.0  United Kingdom        45.0

In [206]:
#2.	Find customers who purchased more than 1000 items in total.
heavy_buyers=df.groupby('Customer ID')['Quantity'].sum()
heavy_buyers=heavy_buyers[heavy_buyers>1000]
heavy_buyers

Customer ID
12347.0    2458
12348.0    2341
12356.0    1591
12357.0    2708
12359.0    1612
           ... 
18260.0    1469
18263.0    1467
18272.0    2044
18283.0    1397
18287.0    1586
Name: Quantity, Length: 1059, dtype: int64

In [214]:
#3.	List all InvoiceNo values where total order value > 1000 GBP.
order_tot=df.groupby('Invoice')['Price'].sum()
high_value_orders = order_tot[order_tot>1000]
high_value_orders


Invoice
536544      2987.72
536592      3612.35
536865      1435.22
536876      3635.97
537237      3713.99
             ...   
C576338     1038.75
C577348     1149.98
C580604    11586.50
C580605    17836.46
C580726     1100.44
Name: Price, Length: 375, dtype: float64

In [216]:
#4. Identify top 5 customers by total revenue.
top_cust=df.groupby('Customer ID')['Price'].sum().sort_values(ascending=False).head()
top_cust

Customer ID
14096.0    41376.33
15098.0    40278.90
14911.0    31060.66
12744.0    25108.89
16029.0    24111.14
Name: Price, dtype: float64

In [218]:
#5. Find all invoices that contain more than 3 line items.
invoice_line_counts=df.groupby('Invoice').size()
invoice_with_plus =invoice_line_counts[invoice_line_counts>3]
invoice_with_plus.head()

Invoice
536365     7
536367    12
536368     4
536370    20
536373    16
dtype: int64

In [220]:
#6. Identify customers who placed orders from multiple countries.
countries_per_customer=df.groupby('Customer ID')['Country'].nunique()
multi_country_customer=countries_per_customer[countries_per_customer>1]
multi_country_customer

Customer ID
12370.0    2
12394.0    2
12417.0    2
12422.0    2
12429.0    2
12431.0    2
12455.0    2
12457.0    2
Name: Country, dtype: int64

In [222]:
#7. Find products with negative Quantity (returns) and their total loss.
returns=df[df['Quantity']<0]
return_loss=returns.groupby('StockCode')['TotalPrice'].sum()
return_loss.head()

StockCode
10002      0.00
10133     -4.20
10134      0.00
10135     -1.25
11001   -237.05
Name: TotalPrice, dtype: float64

In [226]:
#8. List top 5 retured products(by total returned quantity)
returned_qty=returns.groupby('StockCode')['Quantity'].sum().sort_values()
top_5=returned_qty.head()
top_5

StockCode
23843   -80995
23166   -74494
23005   -19201
84347    -9376
23003    -9058
Name: Quantity, dtype: int64

# Part 6: Advanced Analysis

In [239]:
#1.	For each customer, compute:
customer_metric=df.groupby('Customer ID').agg(
    DistinctProducts=('StockCode','nunique'),
    AvgUnitPrice=('Price','mean'),
    Revenue=('TotalPrice','sum'),
    InvoiceCount=('Invoice','nunique')
).sort_values(by='Revenue',ascending=False)

customer_metric.head()
# ○	Distinct products purchased

# ○	Average unit price

# ○	Revenue and invoice count


DistinctProducts  AvgUnitPrice    Revenue  InvoiceCount
Customer ID                                                         
14646.0                   703      2.590029  279489.02            77
18102.0                   151     11.916236  256438.49            62
17450.0                   127      9.458946  187482.17            55
14911.0                  1794      5.261843  132572.62           248
12415.0                   444      3.213136  123725.45            26

In [243]:
#2.	For each product:

# ○	Number of times it appears

# ○	Median UnitPrice

# ○	Revenue per unit

product_metrics=df.groupby('StockCode').agg(
    AppearanceCount=('Invoice','count'),
    MedianUnitPrice=('Price','median'),
    RevenuePerUnit=('TotalPrice','sum')
).sort_values(by='RevenuePerUnit',ascending=False)
product_metrics.head()

AppearanceCount  MedianUnitPrice  RevenuePerUnit
StockCode                                                  
DOT                    710           184.94       206245.48
22423                 2203            12.75       164762.19
47566                 1727             4.95        98302.98
85123A                2313             2.95        97894.50
85099B                2159             2.08        92356.03

In [255]:
#3.	Flag customers with at least one cancellation (InvoiceNo starts with 'C').
cancel_flags=df[df['Invoice'].astype(str).str.startswith('C')]
cancelled_cust=cancel_flags['Customer ID'].unique()
df['HasCancelled']=df['Customer ID'].isin(cancelled_cust)

df[['Customer ID', "HasCancelled"]].drop_duplicates().head()

Customer ID  HasCancelled
0       17850.0          True
9       13047.0          True
26      12583.0          True
46      13748.0         False
65      15100.0          True

In [259]:
#4 4.	Find fully returned invoices (TotalPrice < 0).

invoice_tot=df.groupby('Invoice')['TotalPrice'].sum()
fully_returned_invoic=invoice_tot[invoice_tot<0]
fully_returned_invoic.head()

Invoice
A563186   -11062.06
A563187   -11062.06
C536379      -27.50
C536383       -4.65
C536391     -141.48
Name: TotalPrice, dtype: float64

In [263]:
# 5.	Identify top 10 customers (excluding any with returns).

no_return_df=df[~df['Customer ID'].isin(cancelled_cust)]
top10=no_return_df.groupby('Customer ID')['TotalPrice'].sum().sort_values(ascending=False).head()
top10

Customer ID
16333.0    26626.80
16210.0    21086.30
12433.0    13375.87
17735.0    13110.02
16000.0    12393.70
Name: TotalPrice, dtype: float64

--------------------

In [282]:
# 1.	Simulate missing data: randomly drop 10% of values in UnitPrice and fill with median.

df.loc[df.sample(frac=0.10,random_state=42).index,'UnitPrice']=np.nan

#will fill missing unitprice with median
median_pric=df['Price'].median()
df['Price'].fillna(median_pric,inplace=True)
median_pric

2.08

In [306]:
# 2.	Write a function to return the top 3 selling products for a given country and month.

def top_3_prod(country,year,month):
    temp=df.copy()

    temp['InvoiceDate']=pd.to_datetime(temp['InvoiceDate'])
#enusre data column
    filtered=temp[
        (temp['Country']==country) &
        (temp['InvoiceDate'].dt.year==year) &
        (temp['InvoiceDate'].dt.month==month)
    ]

    prod_sales=filtered.groupby('StockCode')['Quantity'].sum()

    return prod_sales.sort_values(ascending=False).head()

top_3_prod('United Kingdom',2010,12)

StockCode
84077     4571
21212     3236
22834     3202
85123A    3130
22693     2617
Name: Quantity, dtype: int64

In [288]:
# 3.	Use apply to label transactions as:

# ○	"Low" if TotalPrice < 20

# ○	"Medium" if 20 ≤ TotalPrice < 100

# ○	"High" if TotalPrice ≥ 100

df['TotalPrice']=df['Quantity']*df['UnitPrice']

In [300]:
def label_price(value):
    if value<20:
        return 'low'
    elif 20<=value<100:
        return "Medium"
    else:
        return "High"

df['TransactionaLabel'] = df['TotalPrice'].apply(label_price)
df[['TotalPrice','TransactionaLabel']].head()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

TotalPrice TransactionaLabel
0         NaN              High
1         NaN              High
2         NaN              High
3         NaN              High
4         NaN              High